//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpfulFriendMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string Category { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> JobDate { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
